version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    groups:
      charm:
        patterns: ["charm.land/*", "github.com/charmbracelet/*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
